language: android
cache: false

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-23

before_install:
  - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean connectedAndroidTest