package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CATEGORY_DATA.
 */
public class CategoryData {

    private long imageId;
    private Long id;
    private long categoryId;
    /** Not-null value. */
    private String name;

    public CategoryData() {
    }

    public CategoryData(Long id) {
        this.id = id;
    }

    public CategoryData(long imageId, Long id, long categoryId, String name) {
        this.imageId = imageId;
        this.id = id;
        this.categoryId = categoryId;
        this.name = name;
    }

    public long getImageId() {
        return imageId;
    }

    public void setImageId(long imageId) {
        this.imageId = imageId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

}
