package greendao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import greendao.CategoryData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CATEGORY_DATA.
*/
public class CategoryDataDao extends AbstractDao<CategoryData, Long> {

    public static final String TABLENAME = "CATEGORY_DATA";

    /**
     * Properties of entity CategoryData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ImageId = new Property(1, long.class, "imageId", false, "IMAGE_ID");
        public final static Property CategoryId = new Property(2, long.class, "categoryId", false, "CATEGORY_ID");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
    };

    private Query<CategoryData> imageData_CategoryDataListQuery;

    public CategoryDataDao(DaoConfig config) {
        super(config);
    }
    
    public CategoryDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CATEGORY_DATA' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'IMAGE_ID' INTEGER NOT NULL ," + // 1: imageId
                "'CATEGORY_ID' INTEGER NOT NULL ," + // 2: categoryId
                "'NAME' TEXT NOT NULL );"); // 3: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CATEGORY_DATA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CategoryData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getImageId());
        stmt.bindLong(3, entity.getCategoryId());
        stmt.bindString(4, entity.getName());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CategoryData readEntity(Cursor cursor, int offset) {
        CategoryData entity = new CategoryData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // imageId
            cursor.getLong(offset + 2), // categoryId
            cursor.getString(offset + 3) // name
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CategoryData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setImageId(cursor.getLong(offset + 1));
        entity.setCategoryId(cursor.getLong(offset + 2));
        entity.setName(cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CategoryData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CategoryData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "categoryDataList" to-many relationship of ImageData. */
    public List<CategoryData> _queryImageData_CategoryDataList(long imageId) {
        synchronized (this) {
            if (imageData_CategoryDataListQuery == null) {
                QueryBuilder<CategoryData> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ImageId.eq(null));
                imageData_CategoryDataListQuery = queryBuilder.build();
            }
        }
        Query<CategoryData> query = imageData_CategoryDataListQuery.forCurrentThread();
        query.setParameter(0, imageId);
        return query.list();
    }

}
