package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.ImageData;
import greendao.CategoryData;

import greendao.ImageDataDao;
import greendao.CategoryDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imageDataDaoConfig;
    private final DaoConfig categoryDataDaoConfig;

    private final ImageDataDao imageDataDao;
    private final CategoryDataDao categoryDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imageDataDaoConfig = daoConfigMap.get(ImageDataDao.class).clone();
        imageDataDaoConfig.initIdentityScope(type);

        categoryDataDaoConfig = daoConfigMap.get(CategoryDataDao.class).clone();
        categoryDataDaoConfig.initIdentityScope(type);

        imageDataDao = new ImageDataDao(imageDataDaoConfig, this);
        categoryDataDao = new CategoryDataDao(categoryDataDaoConfig, this);

        registerDao(ImageData.class, imageDataDao);
        registerDao(CategoryData.class, categoryDataDao);
    }
    
    public void clear() {
        imageDataDaoConfig.getIdentityScope().clear();
        categoryDataDaoConfig.getIdentityScope().clear();
    }

    public ImageDataDao getImageDataDao() {
        return imageDataDao;
    }

    public CategoryDataDao getCategoryDataDao() {
        return categoryDataDao;
    }

}
